### PR TITLE
SecuredCookie  and PublicIp in LoadBalancer

### LINKED ISSUE #156: Implement "SecuredCookies" parameter in LoadBalancer resource and datasource(s)

### LINKED ISSUE #198: Implement "public_ip" parameter in LoadBalancer resource and datasource(s)
### Current Terraform Version

```
$ terraform version
Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/outscale-dev/outscale v0.5.4
```

### Use-cases
```terraform
terraform {
  required_providers {
    outscale = {
      source  = "outscale-dev/outscale"
      version = "0.5.4"
    }
  }
}

provider "outscale" {
  region = "eu-west-2"
  access_key_id = "REDACTED"
  secret_key_id = "REDACTED"
}
resource "outscale_net" "net02" {
  ip_range = "10.0.0.0/16"
}

resource "outscale_subnet" "subnet02" {
  net_id   = outscale_net.net02.net_id
  ip_range = "10.0.0.0/24"
  tags {
    key   = "Name"
    value = "terraform-security-group-for-load-balancer"
  }
}

resource "outscale_internet_service" "internet_service01" {
  depends_on = [outscale_net.net02]
}

resource "outscale_internet_service_link" "internet_service_link01" {
  internet_service_id = outscale_internet_service.internet_service01.internet_service_id
  net_id              = outscale_net.net02.net_id
}

resource "outscale_route_table" "route_table01" {
  net_id = outscale_net.net02.net_id
  tags {
    key   = "name"
    value = "terraform-load-balancer"
  }
}

resource "outscale_route" "route01" {
  gateway_id           = outscale_internet_service.internet_service01.id
  destination_ip_range = "0.0.0.0/0"
  route_table_id       = outscale_route_table.route_table01.route_table_id
}

resource "outscale_route_table_link" "route_table_link01" {
  route_table_id = outscale_route_table.route_table01.route_table_id
  subnet_id      = outscale_subnet.subnet02.subnet_id
}

resource "outscale_load_balancer" "load_balancer03" {
  load_balancer_name = "inter-facing-private-lbu"
  listeners {
    backend_port           = 80
    backend_protocol       = "TCP"
    load_balancer_protocol = "TCP"
    load_balancer_port     = 80
  }
  listeners {
    backend_port           = 8080
    backend_protocol       = "HTTP"
    load_balancer_protocol = "HTTP"
    load_balancer_port     = 8080
  }
 subnets            = [outscale_subnet.subnet02.subnet_id]
  load_balancer_type = "internet-facing"
  public_ip = "148.245.105.10"
  tags {
    key   = "name"
    value = "internet-facing-private-lbu"
  }
  depends_on = [outscale_route.route01, outscale_route_table_link.route_table_link01]
}

```
### Debug Output

```
╷
│ Error: Unsupported argument
│ 
│   on lbu_publicIp.tf line 58, in resource "outscale_load_balancer" "load_balancer03":
│   58:   public_ip = "148.245.105.10"
│ 
│ An argument named "public_ip" is not expected here.
╵

### PR DESCRIPTION
**Pull request by FredericBerot-Armand**
closes #156 
closes #198

### CODE REVIEW

File: outscale/resource_outscale_load_balancer.go [hunk 1]
```diff
@@ -447,6 +452,53 @@ func resourceOutscaleOAPILoadBalancerCreate_(d *schema.ResourceData, meta interf
...
+	d.SetPartial("access_log")
+	d.SetPartial("health_check")
+	d.SetPartial("backend_vm_ids")
+	d.SetPartial("listeners")
+	d.SetPartial("source_security_group")
+	d.SetPartial("public_ip")
+	d.SetPartial("net_id")
+	d.SetPartial("application_sticky_cookie_policies")
+	d.SetPartial("load_balancer_sticky_cookie_policies")
+
```
Comment (outscale-toa) [inline outscale/resource_outscale_load_balancer.go:488]: ``` d.SetPartial ``` is deprecated in the next version of terraform-SDK, if we can avoid to use it now that will be cool

File: outscale/resource_outscale_load_balancer.go [hunk 2]
```diff
@@ -447,6 +452,53 @@ func resourceOutscaleOAPILoadBalancerCreate_(d *schema.ResourceData, meta interf
...
+		var err error
+		err = resource.Retry(1*time.Minute, func() *resource.RetryError {
+			_, _, err = conn.LoadBalancerApi.UpdateLoadBalancer(
+				context.Background()).UpdateLoadBalancerRequest(req).Execute()
+			if err != nil {
+				return utils.CheckThrottling(err)
+			}
+			return nil
+		})
+
```
Comment (outscale-toa) [inline outscale/resource_outscale_load_balancer.go:504]: I think update request should be call in update function

**Review by outscale-toa — CHANGES_REQUESTED** [review]

File: outscale/resource_outscale_load_balancer.go (hunk 1 above)
Comment (FredericBerot-Armand) [reply outscale/resource_outscale_load_balancer.go:488]: Ok I haven't see that, i remove this ^^

**Review by outscale-toa — APPROVED** [review]
